redis:
  single: #单节点模式
    url: 127.0.0.1:6379
    password: 123456
    database: 0
    timeout: 1000
  masterslave: #主从模式
    master: 127.0.0.1:6379
    slave: 127.0.0.1:6380,127.0.0.1:6381
    password: 123456
    database: 0
    timeout: 1000
  sentinel: #哨兵模式
    masterName: mymaster
    sentinelUrl: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
    password: 123456
    database: 0
    timeout: 1000
    maxIdle: 10
    maxTotal: 100
    maxWaitMillis: 10000
